name: pulse
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2
  file_picker: ^8.3.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.1
  flutter_ai_toolkit: ^0.6.8
  google_generative_ai: ^0.4.6
  flutter_native_splash: ^2.4.4
  awesome_notifications: ^0.10.0
  flutter_launcher_icons: ^0.14.3
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  cloud_firestore: ^5.6.3
  twilio_flutter: ^0.9.0
  firebase_messaging: ^15.2.2
  



  
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
  - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
